version: '2.0'

services:
  aws-ssh:
    image: bibbylong/aws-localproxy-cli:1.0.1-amd64
    container_name: aws-tunnel
    restart: 'no'
    volumes:
      - ./:/data
    network_mode: host
    entrypoint: 
    - '/data/tunnel.sh'
    - 'ssh moxa@localhost -p 5555'

  device-mgmt:
    build: .
    image: bibbylong/device-mgmt:1.0.8-amd64
    container_name: device-mgmt
    volumes:
      - ./:/data
    restart: 'no'
    network_mode: host
    entrypoint:
    - python3
    - ./mgmt.py 

  sample:
    build: .
    image: bibbylong/device-mgmt:1.0.8-amd64
    container_name: cloud-sample
    volumes:
      - ./:/data
    restart: 'no'
    network_mode: host
    entrypoint:
    - python3
    - ./sample.py 
